package adventofcode.day6;

import org.junit.Assert;
import org.junit.Test;

/**
 * @author Mike Schmid
 */
public class Day6Puzzle2Test {

    @Test
    public void solve() throws Exception {
        final String input = "eedadn\n" +
                "drvtee\n" +
                "eandsr\n" +
                "raavrd\n" +
                "atevrs\n" +
                "tsrnev\n" +
                "sdttsa\n" +
                "rasrtv\n" +
                "nssdts\n" +
                "ntnada\n" +
                "svetve\n" +
                "tesnvt\n" +
                "vntsnd\n" +
                "vrdear\n" +
                "dvrsen\n" +
                "enarar";

        Assert.assertEquals("advent", Day6Puzzle2.solve(input));
    }

    @Test
    public void solveReal() throws Exception {
        final String input = "lhyrnfkp\n" +
                "bdxpggwq\n" +
                "owtzswtq\n" +
                "obxtfotk\n" +
                "hvdshmol\n" +
                "kpjqpftg\n" +
                "odyagvec\n" +
                "vqlbxrft\n" +
                "htwenegq\n" +
                "pcfoxgwm\n" +
                "bmnqzuiu\n" +
                "xidteswq\n" +
                "wiizqpqh\n" +
                "vnlueoku\n" +
                "hgzntafs\n" +
                "kfeswcad\n" +
                "lqskhvrj\n" +
                "uguljfpd\n" +
                "dfbmduuu\n" +
                "gajujozo\n" +
                "dckmgouu\n" +
                "hebcfxov\n" +
                "uwamfjjb\n" +
                "fjpuapzj\n" +
                "ygxbvkfm\n" +
                "erbfbfld\n" +
                "rsspowgs\n" +
                "zfxrshqw\n" +
                "gafegcak\n" +
                "lfcluytl\n" +
                "aqmvtdoc\n" +
                "dnjwbcit\n" +
                "jztgwbnc\n" +
                "tcwuxhjh\n" +
                "fpfhkcqo\n" +
                "kachowxl\n" +
                "zlwqlobd\n" +
                "qfbucjco\n" +
                "hsmibqak\n" +
                "ogilflqz\n" +
                "ivgyuvsc\n" +
                "flzagyss\n" +
                "oiiboban\n" +
                "awhilrmt\n" +
                "ayubmyyr\n" +
                "utxexzay\n" +
                "dhmokgfu\n" +
                "rkkbvaev\n" +
                "fvxlzlze\n" +
                "wwdlexhb\n" +
                "yedagwrr\n" +
                "hhlqfqsh\n" +
                "ltudvrke\n" +
                "exhlcdsz\n" +
                "yivivatl\n" +
                "iwtfslic\n" +
                "jwvfrjrv\n" +
                "cxxmyjwc\n" +
                "scmmaybm\n" +
                "btiofois\n" +
                "bhwtwamw\n" +
                "rfukzzou\n" +
                "qeyteivm\n" +
                "ukahvjgq\n" +
                "bgupxqrk\n" +
                "auftcjcm\n" +
                "yjqhlsnq\n" +
                "fnwgotrw\n" +
                "sxlumijz\n" +
                "hcfzkmwn\n" +
                "kcadgqti\n" +
                "qfcjrzdj\n" +
                "eqydvbir\n" +
                "fdobphcp\n" +
                "xekmnluy\n" +
                "clithgmp\n" +
                "ljstbcqd\n" +
                "vxjldlan\n" +
                "mgsggpdd\n" +
                "pjnosake\n" +
                "qqzturnb\n" +
                "leheznzo\n" +
                "ybfofjsq\n" +
                "zoenlucn\n" +
                "gymggaxt\n" +
                "zckaufca\n" +
                "pmedrmhx\n" +
                "msewtqrf\n" +
                "eiplbtmg\n" +
                "oewlpxmw\n" +
                "uunrjsdm\n" +
                "mawiiqul\n" +
                "ixglpexk\n" +
                "fcynrfxy\n" +
                "bzexbifa\n" +
                "mowgbeem\n" +
                "gwfyujhp\n" +
                "jwpuyebl\n" +
                "avtcspem\n" +
                "urrvrlvr\n" +
                "qgvgsknr\n" +
                "opjkhrao\n" +
                "hoxrpptx\n" +
                "qhounvgg\n" +
                "csvdrqqs\n" +
                "csnbvhvz\n" +
                "gpcilcdi\n" +
                "noqqbkxy\n" +
                "smgtokde\n" +
                "rpgdqnyr\n" +
                "qbrogtby\n" +
                "sibulura\n" +
                "ycwjyxep\n" +
                "luoyiblx\n" +
                "otqmbbxz\n" +
                "lupxuwfd\n" +
                "qbinsygw\n" +
                "ywvjhhes\n" +
                "xbmxqhyr\n" +
                "nbkxytyk\n" +
                "orqhztoz\n" +
                "crxujqbz\n" +
                "xodnlvhi\n" +
                "tykaiqin\n" +
                "xozmhtae\n" +
                "xuxnomin\n" +
                "eacuruti\n" +
                "zkkcbhbn\n" +
                "tctjwsog\n" +
                "htgyerci\n" +
                "sgmgiowl\n" +
                "vkawsetx\n" +
                "voynmlmc\n" +
                "fnevibkh\n" +
                "shvbilhc\n" +
                "xracdkcd\n" +
                "fcrdzbbl\n" +
                "sulzfapg\n" +
                "icdtfcqd\n" +
                "bqjkzydz\n" +
                "tablhoxv\n" +
                "xspyzhwx\n" +
                "zwlvjfnh\n" +
                "qnfrpjyb\n" +
                "zvtpcwsy\n" +
                "ucdbrczy\n" +
                "uncwjsxx\n" +
                "ybmlntib\n" +
                "zfhsohus\n" +
                "hahcyiwz\n" +
                "nkfwapvp\n" +
                "dlztazjm\n" +
                "vsbmddos\n" +
                "dxtycpao\n" +
                "cycasgeg\n" +
                "olhbpcvc\n" +
                "ngwsrotj\n" +
                "zcxqpkmi\n" +
                "wshterwt\n" +
                "pbigbqrt\n" +
                "sejncntd\n" +
                "lzfgcsns\n" +
                "husizvtu\n" +
                "rprjazgp\n" +
                "beuzgqlw\n" +
                "tljkixdi\n" +
                "zbyenvlj\n" +
                "ffgyvrbk\n" +
                "lwjuypvf\n" +
                "exnykvdw\n" +
                "mnnvdqay\n" +
                "uefjovqd\n" +
                "zkywlypt\n" +
                "xuwhirkd\n" +
                "hrdnxbrf\n" +
                "eozjuiwn\n" +
                "uxrjjtid\n" +
                "firfnhfa\n" +
                "zzojxpnq\n" +
                "nvurxucq\n" +
                "vdcujaxw\n" +
                "arssafhy\n" +
                "vvsfhzee\n" +
                "ciapvfdc\n" +
                "qdhlukys\n" +
                "ksovlkej\n" +
                "pxrwiwzx\n" +
                "zzfiwfvr\n" +
                "ayoereac\n" +
                "ulpvcnro\n" +
                "rnoikeya\n" +
                "ovhwczvr\n" +
                "ftqdelxp\n" +
                "tlbnplxk\n" +
                "lkgdahfx\n" +
                "mggihwml\n" +
                "ksjwayke\n" +
                "ttuuzpek\n" +
                "eluymfyk\n" +
                "vdxlaxeu\n" +
                "wuvfemmu\n" +
                "yenquvzq\n" +
                "paezsssc\n" +
                "oqippwok\n" +
                "itczzoph\n" +
                "bsccydfh\n" +
                "tushtlcv\n" +
                "rfdmmnmd\n" +
                "hshmdvsj\n" +
                "vvbrlkrw\n" +
                "ugiswkuu\n" +
                "kjussibm\n" +
                "xzsgsnib\n" +
                "upayqkgu\n" +
                "wlzpjyiz\n" +
                "laypqoee\n" +
                "uapvdsne\n" +
                "tthkhvdr\n" +
                "iwqovpna\n" +
                "kfdcmiye\n" +
                "njvzsbvm\n" +
                "srhatweg\n" +
                "jsnkvxpl\n" +
                "zswwzeif\n" +
                "agbamkem\n" +
                "djbqhvbv\n" +
                "vlkjggfu\n" +
                "hswvkmrj\n" +
                "jbysaclf\n" +
                "dzwvvziv\n" +
                "rfczoqnx\n" +
                "nefkqmww\n" +
                "uxjobclu\n" +
                "zwjoigln\n" +
                "hbozuyos\n" +
                "bdozmqbn\n" +
                "vhqqedwc\n" +
                "ljgokudj\n" +
                "zodxojtk\n" +
                "nsulycdw\n" +
                "cxzptacm\n" +
                "cfysgnvq\n" +
                "dyesppsp\n" +
                "tkzkmlvh\n" +
                "oqsdxnkf\n" +
                "ejgaimum\n" +
                "rjmtdinr\n" +
                "vpzintix\n" +
                "gqhymakz\n" +
                "nwvmscpi\n" +
                "hqunkejv\n" +
                "eyhyrcpi\n" +
                "iaflkwqe\n" +
                "tdxrtdhg\n" +
                "hfknwepa\n" +
                "gdxemuby\n" +
                "mkrajouk\n" +
                "ajtitfdq\n" +
                "dwcwpggi\n" +
                "ngimhicq\n" +
                "udxxyuab\n" +
                "zwtszrur\n" +
                "plexfxyv\n" +
                "wazqfmww\n" +
                "vpognhbz\n" +
                "vtifgeio\n" +
                "jldhmfav\n" +
                "uspahejn\n" +
                "likckhyf\n" +
                "jbisjfup\n" +
                "oftrdcwr\n" +
                "jyqefbhm\n" +
                "kvdohlkp\n" +
                "zrumcnji\n" +
                "nmpaanya\n" +
                "sggpmlpb\n" +
                "cegbqkqg\n" +
                "arnnqzsh\n" +
                "saahxqsp\n" +
                "izdwddgg\n" +
                "hfohuypm\n" +
                "yjvknxyf\n" +
                "bvlwdrmj\n" +
                "trqabrzq\n" +
                "pociqnxb\n" +
                "bmjnhhlx\n" +
                "msinoxjy\n" +
                "fooxyuex\n" +
                "pbykwjvs\n" +
                "cjwhfsgq\n" +
                "djzxxxjh\n" +
                "bmjsuoxs\n" +
                "vtzwpjkf\n" +
                "ogwnrdzx\n" +
                "zcnjymzg\n" +
                "pzsfqqex\n" +
                "yqyfsdyw\n" +
                "eekchxvn\n" +
                "ctwktbkp\n" +
                "whqbkrij\n" +
                "tqrtysfa\n" +
                "ymndxpzg\n" +
                "nbiyqgzv\n" +
                "ekstohsw\n" +
                "rljlxgpb\n" +
                "lmrqphro\n" +
                "ouxjemvj\n" +
                "brrhaful\n" +
                "enzzllkv\n" +
                "unmhtfbz\n" +
                "kjraowee\n" +
                "jvvuoahh\n" +
                "tfjcyxok\n" +
                "szgefjvx\n" +
                "rjsmlsly\n" +
                "aznbtehx\n" +
                "idgfmhps\n" +
                "wxhcjufd\n" +
                "rpkutkqw\n" +
                "yyettepo\n" +
                "lflhbnqs\n" +
                "sdobnamv\n" +
                "lpxuusdt\n" +
                "nnlyjlxd\n" +
                "puiriksn\n" +
                "jmaieiag\n" +
                "sklextax\n" +
                "nmznoyfh\n" +
                "ryaeiofl\n" +
                "snluyzji\n" +
                "ppnyiohv\n" +
                "qadwkbhu\n" +
                "ymuksnww\n" +
                "yzrplymh\n" +
                "bdlboxvb\n" +
                "kiefctje\n" +
                "lwvgitsa\n" +
                "urudiexs\n" +
                "tkcxoseq\n" +
                "mqqzubnu\n" +
                "pvrfzuyi\n" +
                "yofpwinb\n" +
                "dvehcoei\n" +
                "xmpjtcgq\n" +
                "eyhneuyt\n" +
                "peronjzx\n" +
                "cveyxrsp\n" +
                "jeybgxfh\n" +
                "aqabkslx\n" +
                "mslqlvuw\n" +
                "tcprsuco\n" +
                "bhuuwrhc\n" +
                "dqxqdqrt\n" +
                "qupeywul\n" +
                "mvhlcjmv\n" +
                "ghtpieve\n" +
                "xiifboln\n" +
                "mcxhnbib\n" +
                "oixetmpu\n" +
                "xmpgndni\n" +
                "bjqdnvrt\n" +
                "lutqzgkt\n" +
                "glegjyov\n" +
                "qtqeqsvf\n" +
                "adbjbzxh\n" +
                "tevysrxy\n" +
                "wjwvsawn\n" +
                "iutrrjqw\n" +
                "nmnpjusp\n" +
                "iybibkla\n" +
                "qvnewyit\n" +
                "nmailspe\n" +
                "wtlydtcs\n" +
                "ghormkll\n" +
                "mfvxauyb\n" +
                "eaqgafon\n" +
                "raygyorv\n" +
                "krmjzdqa\n" +
                "waofjzzp\n" +
                "ufcveijp\n" +
                "gzqrvyhl\n" +
                "rirdkmvf\n" +
                "miubcwxg\n" +
                "yuvsrfgp\n" +
                "izeizudk\n" +
                "incwrrjq\n" +
                "ereewgbm\n" +
                "bmvormqn\n" +
                "parghyrt\n" +
                "vhttgvgd\n" +
                "dhasugne\n" +
                "mgbzfmpu\n" +
                "mybpdtrg\n" +
                "szjzhabk\n" +
                "rpkzqopr\n" +
                "jpqmwony\n" +
                "reneqkqz\n" +
                "xnocadlb\n" +
                "mmcauasf\n" +
                "ngdfnobk\n" +
                "adleanyx\n" +
                "dcncwdwh\n" +
                "gnpybbkq\n" +
                "aulbasht\n" +
                "njjpuptw\n" +
                "poxmnfuy\n" +
                "qnzqruza\n" +
                "vtkgllko\n" +
                "avewkizl\n" +
                "iocvvprq\n" +
                "qcqsdczw\n" +
                "ehnoydws\n" +
                "wmlnznpe\n" +
                "arjqeqqe\n" +
                "gnexqzsj\n" +
                "tijgmcig\n" +
                "pbfsvwux\n" +
                "gugnfhbo\n" +
                "qmyqyvkm\n" +
                "fgtckaac\n" +
                "zoeazigt\n" +
                "qxpizwxb\n" +
                "poovcaos\n" +
                "aawpkglf\n" +
                "fhsdishc\n" +
                "hxyujvgl\n" +
                "hbmpgqdy\n" +
                "xuvopjga\n" +
                "mrfqakoj\n" +
                "gbhoepag\n" +
                "fxgqxppa\n" +
                "rlnyrcnq\n" +
                "idgaetyt\n" +
                "yiknwvkb\n" +
                "dsveccnf\n" +
                "grldsgay\n" +
                "ydlhxzbg\n" +
                "zxcrqglb\n" +
                "szmfqqog\n" +
                "siukuawi\n" +
                "qjpfebjv\n" +
                "gyixkejo\n" +
                "pqmsfrpp\n" +
                "zbmxowwd\n" +
                "okohvtgz\n" +
                "prltqpac\n" +
                "rdlzijcf\n" +
                "kbcxibir\n" +
                "yqgolykj\n" +
                "avkdphjz\n" +
                "cuccogmn\n" +
                "ihokkctr\n" +
                "neqbogzz\n" +
                "cpsqlwff\n" +
                "nxufhdhw\n" +
                "fepxflir\n" +
                "rafrmamv\n" +
                "xoqiyxoz\n" +
                "jtskidty\n" +
                "djervlek\n" +
                "jahstrlh\n" +
                "ityywfmz\n" +
                "ukkwnapa\n" +
                "mxwktajk\n" +
                "vnfnneqe\n" +
                "webgudjj\n" +
                "cxtwfeul\n" +
                "tnzwvzvv\n" +
                "oxgxwsau\n" +
                "ihivmxwd\n" +
                "xoatylxh\n" +
                "wdcaatlt\n" +
                "cqopcsvz\n" +
                "zwdmmndm\n" +
                "gogrwieu\n" +
                "mqsdxygv\n" +
                "sqpcymua\n" +
                "jmazibct\n" +
                "yknevica\n" +
                "ehzldixx\n" +
                "dyjoghsf\n" +
                "ikakjhau\n" +
                "cuwcflmn\n" +
                "dqxjbpws\n" +
                "hbtgfrfd\n" +
                "bksloymh\n" +
                "wdhpbuyy\n" +
                "wlyulitl\n" +
                "glgpckqa\n" +
                "wbyolght\n" +
                "ccajptsy\n" +
                "cpaitxsf\n" +
                "aczruvmp\n" +
                "yktaqanj\n" +
                "sftudeog\n" +
                "fnpajmtc\n" +
                "avbddclh\n" +
                "ktmfntzj\n" +
                "qykluqnl\n" +
                "whvdmwsi\n" +
                "nsitvglv\n" +
                "pypxhjfc\n" +
                "fnmwqzrq\n" +
                "etnoezmk\n" +
                "uvsspzfl\n" +
                "igdiwpjw\n" +
                "doajkjck\n" +
                "jwiwvwot\n" +
                "wkbkruzo\n" +
                "thfeynyj\n" +
                "kenadzbr\n" +
                "jthejixe\n" +
                "gwlzgutb\n" +
                "lwmjqqah\n" +
                "xtkxdnoj\n" +
                "kohmprey\n" +
                "obqzhykf\n" +
                "bzvkkedg\n" +
                "mrmdmdou\n" +
                "kiacwglo\n" +
                "xnmfwghi\n" +
                "crmeazdo\n" +
                "hirvjnhc\n" +
                "bcghamtz\n" +
                "dgfxbelb\n" +
                "jrtrcvio\n" +
                "dyfvttud\n" +
                "kkvxqzjm\n" +
                "rcydrpri\n" +
                "llamtmut\n" +
                "rwdhzdur\n" +
                "iikojxou\n" +
                "xvillkbg\n" +
                "jorzdbqp\n" +
                "tjryewvm\n" +
                "jlkvxdmm\n" +
                "mdsaatua\n" +
                "shrxrfdp\n" +
                "fpbvqxch\n" +
                "emujcgto\n" +
                "gzbrndna\n" +
                "viqcxvhf\n" +
                "gpvbnigj\n" +
                "wpztmzdi\n" +
                "jpatgigc\n" +
                "ozrmpbyl\n" +
                "apbfznky\n" +
                "wkzvbnof\n" +
                "nhbcplqc\n" +
                "edehgyfa\n" +
                "xgdotibf\n" +
                "tytmwmjd\n" +
                "jxkqfkce\n" +
                "ferkxtgn\n" +
                "cyppemii\n" +
                "vzszchcr\n" +
                "fiyqcfzj\n" +
                "kqsjswts\n" +
                "xxmfvbnb\n" +
                "kpditjko\n" +
                "qsdseuur\n" +
                "wfergpjs\n" +
                "vmwkuxhi\n" +
                "qkogsmfn\n" +
                "batcpncv\n" +
                "llpvhscr\n" +
                "izuikdze\n" +
                "szujrspz\n" +
                "kgocdjgb\n" +
                "euqheofn\n" +
                "kyzbxxqo\n" +
                "oyislbdo";

        Assert.assertEquals("pljvorrk", Day6Puzzle2.solve(input));
    }

}